CREATE TABLE FRegistroExemplares (
    FK_DTEMPO_PK_TEMPO VARCHAR(36) NOT NULL,
    FK_GEOGRAFICA_PK_GEOGRAFICA VARCHAR(36) NOT NULL,
    FK_ENDERECO_PK_ENDERECO VARCHAR(36) NOT NULL,
    FK_IES_PK_IES VARCHAR(36) NOT NULL,
    FK_BIBLIOTECA_PK_BIBLIOTECA VARCHAR(36) NOT NULL,
    QT_PERIODICO_ELETRONICO INT NOT NULL,
    QT_LIVRO_ELETRONICO INT NOT NULL,
    PRIMARY KEY (
        FK_DTEMPO_PK_TEMPO,
        FK_GEOGRAFICA_PK_GEOGRAFICA,
        FK_ENDERECO_PK_ENDERECO,
        FK_IES_PK_IES,
        FK_BIBLIOTECA_PK_BIBLIOTECA
    ),
    FOREIGN KEY (FK_DTEMPO_PK_TEMPO) REFERENCES D_TEMPO(PK_TEMPO),
    FOREIGN KEY (FK_GEOGRAFICA_PK_GEOGRAFICA) REFERENCES D_GEOGRAFICA(PK_GEOGRAFICA),
    FOREIGN KEY (FK_ENDERECO_PK_ENDERECO) REFERENCES D_ENDERECO(PK_ENDERECO),
    FOREIGN KEY (FK_IES_PK_IES) REFERENCES D_IES(PK_IES),
    FOREIGN KEY (FK_BIBLIOTECA_PK_BIBLIOTECA) REFERENCES D_BIBLIOTECA(PK_BIBLIOTECA)
);
--

