INSERT INTO FRegistroExemplares (
    FK_DTEMPO_PK_TEMPO,
    FK_GEOGRAFICA_PK_GEOGRAFICA,
    FK_ENDERECO_PK_ENDERECO,
    FK_IES_PK_IES,
    FK_BIBLIOTECA_PK_BIBLIOTECA,
    QT_PERIODICO_ELETRONICO,
    QT_LIVRO_ELETRONICO
)
SELECT
    DT.PK_TEMPO AS FK_DTEMPO_PK_TEMPO,
    DG.PK_GEOGRAFICA AS FK_GEOGRAFICA_PK_GEOGRAFICA,
    DE.PK_ENDERECO AS FK_ENDERECO_PK_ENDERECO,
    DI.PK_IES AS FK_IES_PK_IES,
    DB.PK_BIBLIOTECA AS FK_BIBLIOTECA_PK_BIBLIOTECA,
    MT.QT_PERIODICO_ELETRONICO,
    MT.QT_LIVRO_ELETRONICO
FROM mytable MT
JOIN D_TEMPO DT ON MT.NU_ANO_CENSO = DT.NU_ANO_CENSO
JOIN D_GEOGRAFICA DG ON (
    MT.NO_REGIAO_IES = DG.NO_REGIAO_IES AND 
    MT.CO_REGIAO_IES = DG.CO_REGIAO_IES AND 
    MT.NO_UF_IES = DG.NO_UF_IES AND 
    MT.SG_UF_IES = DG.SG_UF_IES AND 
    MT.CO_UF_IES = DG.CO_UF_IES AND 
    MT.NO_MUNICIPIO_IES = DG.NO_MUNICIPIO_IES AND 
    MT.CO_MUNICIPIO_IES = DG.CO_MUNICIPIO_IES AND 
    MT.IN_CAPITAL_IES = DG.IN_CAPITAL_IES AND 
    MT.NO_MESORREGIAO_IES = DG.NO_MESORREGIAO_IES AND 
    MT.CO_MESORREGIAO_IES = DG.CO_MESORREGIAO_IES AND 
    MT.NO_MICRORREGIAO_IES = DG.NO_MICRORREGIAO_IES AND 
    MT.CO_MICRORREGIAO_IES = DG.CO_MICRORREGIAO_IES
)
JOIN D_ENDERECO DE ON (
    MT.DS_ENDERECO_IES = DE.DS_ENDERECO_IES AND 
    MT.DS_NUMERO_ENDERECO_IES = DE.DS_NUMERO_ENDERECO_IES AND 
    MT.DS_COMPLEMENTO_ENDERECO_IES = DE.DS_COMPLEMENTO_ENDERECO_IES AND 
    MT.NO_BAIRRO_IES = DE.NO_BAIRRO_IES AND 
    MT.NU_CEP_IES = DE.NU_CEP_IES
)
JOIN D_IES DI ON (
    MT.NO_IES = DI.NO_IES AND 
    MT.SG_IES = DI.SG_IES AND 
    MT.CO_IES = DI.CO_IES AND 
    MT.TP_ORGANIZACAO_ACADEMICA = DI.TP_ORGANIZACAO_ACADEMICA AND 
    MT.TP_CATEGORIA_ADMINISTRATIVA = DI.TP_CATEGORIA_ADMINISTRATIVA AND 
    MT.CO_MANTENEDORA = DI.CO_MANTENEDORA
)
JOIN D_BIBLIOTECA DB ON (
    MT.IN_ACESSO_PORTAL_CAPES = DB.IN_ACESSO_PORTAL_CAPES AND 
    MT.IN_ACESSO_OUTRAS_BASES = DB.IN_ACESSO_OUTRAS_BASES AND 
    MT.IN_ASSINA_OUTRA_BASE = DB.IN_ASSINA_OUTRA_BASE AND 
    MT.IN_REPOSITORIO_INSTITUCIONAL = DB.IN_REPOSITORIO_INSTITUCIONAL AND 
    MT.IN_BUSCA_INTEGRADA = DB.IN_BUSCA_INTEGRADA AND 
    MT.IN_SERVICO_INTERNET = DB.IN_SERVICO_INTERNET AND 
    MT.IN_PARTICIPA_REDE_SOCIAL = DB.IN_PARTICIPA_REDE_SOCIAL AND 
    MT.IN_CATALOGO_ONLINE = DB.IN_CATALOGO_ONLINE
);
