SELECT 
    IN_ACESSO_PORTAL_CAPES,
    IN_ACESSO_OUTRAS_BASES,
    IN_ASSINA_OUTRA_BASE,
    IN_REPOSITORIO_INSTITUCIONAL,
    IN_BUSCA_INTEGRADA,
    IN_SERVICO_INTERNET,
    IN_PARTICIPA_REDE_SOCIAL,
    IN_CATALOGO_ONLINE,
    UUID() as PK_BIBLIOTECA 
FROM `mytable` 
WHERE 1 
GROUP BY 
    IN_ACESSO_PORTAL_CAPES,
    IN_ACESSO_OUTRAS_BASES,
    IN_ASSINA_OUTRA_BASE,
    IN_REPOSITORIO_INSTITUCIONAL,
    IN_BUSCA_INTEGRADA,
    IN_SERVICO_INTERNET,
    IN_PARTICIPA_REDE_SOCIAL,
    IN_CATALOGO_ONLINE;
