SELECT 
    DS_ENDERECO_IES,
    DS_NUMERO_ENDERECO_IES,
    DS_COMPLEMENTO_ENDERECO_IES,
    NO_BAIRRO_IES,
    NU_CEP_IES,
    UUID() as PK_ENDERECO 
FROM `mytable` 
WHERE 1 
GROUP BY 
    DS_ENDERECO_IES,
    DS_NUMERO_ENDERECO_IES,
    DS_COMPLEMENTO_ENDERECO_IES,
    NO_BAIRRO_IES,
    NU_CEP_IES;
