SELECT 
    NO_REGIAO_IES,
    CO_REGIAO_IES,
    NO_UF_IES,
    SG_UF_IES,
    CO_UF_IES,
    NO_MUNICIPIO_IES,
    CO_MUNICIPIO_IES,
    IN_CAPITAL_IES,
    NO_MESORREGIAO_IES,
    CO_MESORREGIAO_IES,
    NO_MICRORREGIAO_IES,
    CO_MICRORREGIAO_IES,
    UUID() as PK_GEOGRAFICA 
FROM `mytable` 
WHERE 1 
GROUP BY 
    NO_REGIAO_IES,
    CO_REGIAO_IES,
    NO_UF_IES,
    SG_UF_IES,
    CO_UF_IES,
    NO_MUNICIPIO_IES,
    CO_MUNICIPIO_IES,
    IN_CAPITAL_IES,
    NO_MESORREGIAO_IES,
    CO_MESORREGIAO_IES,
    NO_MICRORREGIAO_IES,
    CO_MICRORREGIAO_IES;
